name: humble-package
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Create ROS 2 workspace
        shell: bash -eux {0}
        run: mkdir -p ros-workspace/src

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ros-workspace/src/wasm_publisher
      
      - name: Install CMake 3.24.4
        shell: bash
        run: |
            sudo apt-get remove --purge --auto-remove cmake -y
            wget https://github.com/Kitware/CMake/releases/download/v3.24.4/cmake-3.24.4-linux-x86_64.sh
            chmod +x cmake-3.24.4-linux-x86_64.sh
            sudo mkdir /opt/cmake
            sudo ./cmake-3.24.4-linux-x86_64.sh --prefix=/opt/cmake --skip-license
            echo "/opt/cmake/bin" >> $GITHUB_PATH

      # Runs action and builds package
      - name: Cross-compile package
        uses: jeff-hykin/ros2wasm-builder@1.3
        with:
          package: wasm_publisher
          ros_distro: 'humble'
          debug_mode: false
