name: humble-package
on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build-package:
    runs-on: ubuntu-22.04

    steps:
      - name: Create ROS 2 workspace
        shell: bash -eux {0}
        run: mkdir -p ros-workspace/src

      # Clone this repo
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ros-workspace/src/wasm_publisher
      
      # Runs action and builds package
      - name: Cross-compile package
        uses: aggie-tool-kit/ros2wasm-builder@0.1.3.4
        with:
          package: wasm_publisher
          ros_distro: 'humble'
          debug_mode: false
